### ISSUE TITLE
Hello! 您分享的用于CH32V208的NFC方案可否于RFID-RC522与V208杜邦线连接使用

### ISSUE THREAD

**Issue by JohnShen04** [smartmx/smartmx#1]
您分享的PCB是将NFC读写器与ch32v208打在一起，可否用RFID-RC522代替读写器使用？

**Comment by smartmx** [comment]
WCH的NFC是采用两个IO通过发送互补PWM的方式，通过额外增加的模拟解码电路来省掉RC522类似的NFC读写器芯片。一般实体卡都可以使用，但是手机或者手表模拟的卡不能使用，兼容性较差。
如果你准备使用RC522，那么不必参考WCH的电路。

**Comment by JohnShen04** [comment]
谢谢您的回复！

**Comment by JohnShen04** [comment]
麻烦问一下要是想照着您的PCB打板的话，物料清单之类的在哪里可以找到哇

**Comment by smartmx** [comment]
仓库里有AD源文件，可以自己导出。
